modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Fexcraft/FVP"
[[mods]]
modId="fvtm"
version="3.x.x"
displayName="Fex's Vehicle Pack"
displayURL="https://fexcraft.net/wiki/mod/fvtm" 
#credits="" #optional
authors="FEX___96"
displayTest="IGNORE_ALL_VERSION"

description='''A FVTM pack containing vehicles made by FEX___96.'''
